# Generated by Django 3.1.7 on 2021-03-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boba',
            name='business',
            field=models.CharField(default='', help_text='Enter store/cafe name', max_length=40),
        ),
    ]
